name: Publish React Native Package

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to publish from'
        required: true
        default: 'main'

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to NPM
        run: |
          git config user.email "beachball_bot@passage.id"
          git config user.name "Beachball Machine Account"
          git remote set-url origin https://$GITHUB_ACTOR:$PAT@github.com/$GITHUB_REPOSITORY.git
          npm run beachball:publish -- --token "$NPM_ACCESS_TOKEN"
        env:
          NPM_ACCESS_TOKEN: ${{ env.NPM_ACCESS_TOKEN }}
